server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: debug

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
